config/routes.rb
Rails.application.routes.draw do
  resources :ram_entries
  resources :estimation_templates
  resources :estimations
  resources :milestones
  resources :roadmaps
  resources :expert_forms
  resources :form_templates
  resources :rounds
  resources :delphi_estimations
  resources :resource_allocation_matrices
  resources :resources
  resources :roles
  resources :types
  resources :subtasks
  resources :workpackages
  resources :tasks
  resources :components
  resources :moduls
  resources :subproducts
  resources :resource_breakdown_structures
  resources :product_breakdown_structures
  resources :work_breakdown_structures
  resources :projects

  get '/work_breakdown_structures/:id/chart' => 'work_breakdown_structures#chart', as: 'chart_work_breakdown_structure'
  get '/product_breakdown_structures/:id/chart' => 'product_breakdown_structures#chart', as: 'chart_product_breakdown_structure'
  get '/resource_breakdown_structures/:id/chart' => 'resource_breakdown_structures#chart', as: 'chart_resource_breakdown_structure'

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
	belongs_to :modul
	belongs_to :ram_entry
	has_one :milestone, dependent: :destroy
end

app/models/estimation.rb
class Estimation < ActiveRecord::Base
	has_one :workpackage
	belongs_to :expert_form
end

app/models/expert_form.rb
class ExpertForm < ActiveRecord::Base
	belongs_to :round
	has_many :estimations, dependent: :destroy
end

app/models/form_template.rb
class FormTemplate < ActiveRecord::Base
	belongs_to :round
	has_many :estimation_templates, dependent: :destroy
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
	belongs_to :component
end

app/models/modul.rb
class Modul < ActiveRecord::Base
	belongs_to :subproduct
	has_many :components, dependent: :destroy
end

app/models/product_breakdown_structure.rb
class ProductBreakdownStructure < ActiveRecord::Base
	belongs_to :project
	has_many :subproducts, dependent: :destroy, :foreign_key => "pbs_id"
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_one :work_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :product_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :roadmap, dependent: :destroy, :foreign_key => "p_id"
	has_one :delphi_estimation, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_allocation_matrix, dependent: :destroy, :foreign_key => "p_id"
end

app/models/ram_entry.rb
class RamEntry < ActiveRecord::Base
	belongs_to :workpackage
	has_one :resource
	has_one :component
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :role
	belongs_to :ram_entry
	validates :quantitiy, :numericality => {:only_integer => true}
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
	belongs_to :project
	has_many :milestones, dependent: :destroy
end

app/models/role.rb
class Role < ActiveRecord::Base
	belongs_to :type
	has_many :resources, dependent: :destroy
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :delphi_estimation
	has_many :expert_forms, dependent: :destroy
	has_one :form_template, dependent: :destroy
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
	belongs_to :product_breakdown_structure
	has_many :moduls, dependent: :destroy
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
	belongs_to :task
	has_many :workpackages, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :work_breakdown_structure
	has_many :subtasks, dependent: :destroy
end

app/models/type.rb
class Type < ActiveRecord::Base
	belongs_to :resource_breakdown_structer
	has_many :roles, dependent: :destroy
end

app/models/workpackage.rb
class Workpackage < ActiveRecord::Base
	belongs_to :subtask
	has_one :ram_entry, dependent: :destroy
	belongs_to :estimation
	belongs_to :estimation_template
end

app/controllers/product_breakdown_structures_controller.rb
class ProductBreakdownStructuresController < ApplicationController
  before_action :set_product_breakdown_structure, only: [:show, :edit, :update, :destroy, :chart]

  # GET /product_breakdown_structures
  # GET /product_breakdown_structures.json
  def index
    @product_breakdown_structures = ProductBreakdownStructure.all
  end

  # GET /product_breakdown_structures/1
  # GET /product_breakdown_structures/1.json
  def show
  end

  def chart
    product_breakdown_chart
  end
  # GET /product_breakdown_structures/new
  def new
    @product_breakdown_structure = ProductBreakdownStructure.new
  end

  # GET /product_breakdown_structures/1/edit
  def edit
  end

  # POST /product_breakdown_structures
  # POST /product_breakdown_structures.json
  def create
    @product_breakdown_structure = ProductBreakdownStructure.new(product_breakdown_structure_params)

    respond_to do |format|
      if @product_breakdown_structure.save
        format.html { redirect_to @product_breakdown_structure, notice: 'Product Breakdown Structure wurde erfolgreich angelegt' }
        format.json { render :show, status: :created, location: @product_breakdown_structure }
      else
        format.html { render :new }
        format.json { render json: @product_breakdown_structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_breakdown_structures/1
  # PATCH/PUT /product_breakdown_structures/1.json
  def update
    respond_to do |format|
      if @product_breakdown_structure.update(product_breakdown_structure_params)
        format.html { redirect_to @product_breakdown_structure, notice: 'Product Breakdown Structure wurde erfolgreich aktualisiert' }
        format.json { render :show, status: :ok, location: @product_breakdown_structure }
      else
        format.html { render :edit }
        format.json { render json: @product_breakdown_structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_breakdown_structures/1
  # DELETE /product_breakdown_structures/1.json
  def destroy
    @product_breakdown_structure.destroy
    respond_to do |format|
      format.html { redirect_to product_breakdown_structures_url, notice: 'Product Breakdown Structure wurde erfolgreich gelöscht' }
      format.json { head :no_content }
    end
  end

  def product_breakdown_chart
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Name')
    data_table.new_column('string', 'Vorgänger')
    data_table.new_column('string', 'Paket')
    
    project = Project.find_by_id(@product_breakdown_structure.p_id)
    data_table.add_rows([[project.name,'','Produkt']])
    subproducts = Subproduct.where(pbs_id: @product_breakdown_structure.id)
    subproducts.each do |subproduct|
      #<div style="background-color:#ff00ff">
      data_table.add_rows([[subproduct.name, project.name,'Teilprodukt']])
      #data_table.setRowProperty(3, 'style', 'background: #FF0000');
      moduls = Modul.where(subproduct_id: subproduct.id)
      moduls.each do |modul|
        data_table.add_rows([[modul.name,subproduct.name,'Modul']])
        components = Component.where(modul_id: modul.id)
        components.each do |component|
          data_table.add_rows([[component.name,modul.name,'Komponente']])
        end
      end
    end
    options = {allowHtml:true, tooltip: {isHtml: true}}
    @pbs_chart = GoogleVisualr::Interactive::OrgChart.new(data_table, options)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_breakdown_structure
      @product_breakdown_structure = ProductBreakdownStructure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_breakdown_structure_params
      params.require(:product_breakdown_structure).permit(:p_id)
    end
end

app/helpers/product_breakdown_structures_helper.rb
module ProductBreakdownStructuresHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/product_breakdown_structures/_form.html.erb
<%= form_for(@product_breakdown_structure) do |f| %>
  <% if @product_breakdown_structure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_breakdown_structure.errors.count, "error") %> prohibited this product_breakdown_structure from being saved:</h2>

      <ul>
      <% @product_breakdown_structure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :p_id %><br>
    <%= f.number_field :p_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_breakdown_structures/chart.html.erb
<%project = Project.find_by_id(@product_breakdown_structure.p_id) %>
<h1>
	<%= project.name+'-PBS Chart' %>
	<%= link_to 'Zurück', product_breakdown_structure_path, :id=>'btn', :class=> 'btn btn-sm btn-danger pull-right'%>
</h1>
      
<div id='pbs_chart'></div>
  <%= render_chart @pbs_chart, 'pbs_chart' %>

app/views/product_breakdown_structures/edit.html.erb
<%project = Project.find_by_id(@product_breakdown_structure.p_id) %>
<h1>
	<%= project.name+'-PBS' %>
	<%= link_to 'Zurück', product_breakdown_structure_path, :id=>'btn', :class=> 'btn btn-sm btn-danger pull-right'%>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Produkt</th>
      <th>Teilprodukt</th>
      <th>Modul</th>
      <th>Komponente</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

  </tbody>
  <tr id="uno">
	    <td id="middle"><%=project.name %></td>
	    <td><% @subproduct = Subproduct.new %>
	    	<div class = "form-inline">
	    		<%= form_for(@subproduct) do |f| %>
  				<%= f.hidden_field :pbs_id, :value => @product_breakdown_structure.id %> 
  				<div class="form-group">
	  				<div class="field">
	    				<%= f.text_field :name, :class => "form-control input-sm", :placeholder => "Neues Teilprodukt"%>
	  				</div>
  				</div>
	  			<div class="form-group">
	  				<div class="actions">
	  					<%= f.submit "Anlegen", class: "btn btn-xs btn-success" %>
	  				</div>
  				</div>
				<% end %>
			</div>
	    </td>
	    <td colspan="3"></td>
	</tr>
	<% subproducts = Subproduct.where(pbs_id: @product_breakdown_structure.id) %>
	<% subproductNumber = 0 %>
	<% subproducts.each do |subproduct| %>
	<tr id="dos">
		<% subproductNumber = subproductNumber+1 %>
	    <td id="middle"><%=subproductNumber %></td>
	    <td id="middle"><%=subproduct.name %></td>
	    <td><% @modul = Modul.new %>
	    	<div class = "form-inline">
	    		<%= form_for(@modul) do |f| %>
  				<%= f.hidden_field :subproduct_id, :value => subproduct.id %> 
  				<div class="form-group">
	  				<div class="field">
	    				<%= f.text_field :name, :class => "form-control input-sm", :placeholder => "Neues Modul"%>
	  				</div>
  				</div>
	  			<div class="form-group">
	  				<div class="actions">
	  					<%= f.submit "Anlegen", class: "btn btn-xs btn-success" %>
	  				</div>
  				</div>
				<% end %>
			</div>
	    </td>
	    <td colspan="1"></td>
	    <td><%= link_to 'Löschen', subproduct, method: :delete, data: { confirm: 'Sind Sie sicher?' }, :class=> 'btn btn-xs btn-danger' %></td>
	</tr>
	<% moduls = Modul.where(subproduct_id: subproduct.id) %>
	<% modulNumber = 0 %>
	<% moduls.each do |modul| %>
	<tr id="tres">
		<% modulNumber = modulNumber+1 %>
	    <td></td>
	    <td id="middle"><%=subproductNumber.to_s+'.'+modulNumber.to_s %></td>
	    <td id="middle"><%=modul.name %></td>
	    <td><% @component = Component.new %>
	    	<div class = "form-inline">
	    		<%= form_for(@component) do |f| %>
  				<%= f.hidden_field :modul_id, :value => modul.id %> 
  				<div class="form-group">
	  				<div class="field">
	    				<%= f.text_field :name, :class => "form-control input-sm", :placeholder => "Neue Komponente"%>
	  				</div>
  				</div>
	  			<div class="form-group">
	  				<div class="actions">
	  					<%= f.submit "Anlegen", class: "btn btn-xs btn-success" %>
	  				</div>
  				</div>
				<% end %>
			</div>
		</td>
	    <td><%= link_to 'Löschen', modul, method: :delete, data: { confirm: 'Sind Sie sicher?' }, :class=> 'btn btn-xs btn-danger' %></td>
	</tr>
	    <% components = Component.where(modul_id: modul.id) %>
	    <% componentNumber = 0 %>
	    <% components.each do |component| %>
	<tr>
		<% componentNumber = componentNumber+1 %>
		<td colspan="2"></td>
	    <td id="middle"><%=subproductNumber.to_s+'.'+modulNumber.to_s+'.'+componentNumber.to_s %></td>
	    <td id="middle"><%=component.name %></td>
	    <td><%= link_to 'Löschen', component, method: :delete, data: { confirm: 'Sind Sie sicher?' }, :class=> 'btn btn-xs btn-danger' %></td>
	  </td>
	</tr>
	<% end %>
	<% end %>
	<% end %>
  </tbody>
</table>

app/views/product_breakdown_structures/index.html.erb
<h1>Listing Product Breakdown Structures</h1>

<table>
  <thead>
    <tr>
      <th>P</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_breakdown_structures.each do |product_breakdown_structure| %>
      <tr>
        <td><%= product_breakdown_structure.p_id %></td>
        <td><%= link_to 'Show', product_breakdown_structure %></td>
        <td><%= link_to 'Edit', edit_product_breakdown_structure_path(product_breakdown_structure) %></td>
        <td><%= link_to 'Destroy', product_breakdown_structure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product breakdown structure', new_product_breakdown_structure_path %>

app/views/product_breakdown_structures/new.html.erb
<h1>New Product Breakdown Structure</h1>

<%= render 'form' %>

<%= link_to 'Back', product_breakdown_structures_path %>

app/views/product_breakdown_structures/show.html.erb
<%project = Project.find_by_id(@product_breakdown_structure.p_id) %>
<h1>
	<%= project.name+'-PBS' %>
	<%= link_to 'Projekt', project_path(@product_breakdown_structure), :id=>'btn', :class=> 'btn btn-sm btn-danger pull-right'%>
	<%= link_to 'Bearbeiten', edit_product_breakdown_structure_path(@product_breakdown_structure), :id=> 'btn', :class=> 'btn btn-sm btn-success pull-right'%>
	<%= link_to 'Chart', chart_product_breakdown_structure_path(@product_breakdown_structure), :id=>'btn', :class=> 'btn btn-sm btn-primary pull-right'%>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Produkt</th>
      <th>Teilprodukt</th>
      <th>Modul</th>
      <th>Komponente</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <tr id="uno">
	    <td><%=project.name %></td>
	    <td colspan="5"></td>
	</tr>
	<% subproducts = Subproduct.where(pbs_id: @product_breakdown_structure.id) %>
	<% subproductNumber = 0 %>
	<% subproducts.each do |subproduct| %>
	<tr id="dos">
		<% subproductNumber = subproductNumber+1 %>
	    <td><%=subproductNumber %></td>
	    <td><%=subproduct.name %></td>
	    <td colspan="4"></td>
	</tr>
	<% moduls = Modul.where(subproduct_id: subproduct.id) %>
	<% modulNumber = 0 %>
	<% moduls.each do |modul| %>
	<tr id="tres">
		<% modulNumber = modulNumber+1 %>
	    <td></td>
	    <td><%=subproductNumber.to_s+'.'+modulNumber.to_s %></td>
	    <td><%=modul.name %></td>
	    <td colspan="2"></td>
	</tr>
	    <% components = Component.where(modul_id: modul.id) %>
	    <% componentNumber = 0 %>
	    <% components.each do |component| %>
	<tr>
		<% componentNumber = componentNumber+1 %>
		<td colspan="2"></td>
	    <td><%=subproductNumber.to_s+'.'+modulNumber.to_s+'.'+componentNumber.to_s %></td>
	    <td><%=component.name %></td>
	    <td></td>
	  </td>
	</tr>
	<% end %>
	<% end %>
	<% end %>
  </tbody>
</table>