config/routes.rb
Rails.application.routes.draw do
  resources :ram_entries
  resources :estimation_templates
  resources :estimations
  resources :milestones
  resources :roadmaps
  resources :expert_forms
  resources :form_templates
  resources :rounds
  resources :delphi_estimations
  resources :resource_allocation_matrices
  resources :resources
  resources :roles
  resources :types
  resources :subtasks
  resources :workpackages
  resources :tasks
  resources :components
  resources :moduls
  resources :subproducts
  resources :resource_breakdown_structures
  resources :product_breakdown_structures
  resources :work_breakdown_structures
  resources :projects

  get '/work_breakdown_structures/:id/chart' => 'work_breakdown_structures#chart', as: 'chart_work_breakdown_structure'
  get '/product_breakdown_structures/:id/chart' => 'product_breakdown_structures#chart', as: 'chart_product_breakdown_structure'
  get '/resource_breakdown_structures/:id/chart' => 'resource_breakdown_structures#chart', as: 'chart_resource_breakdown_structure'

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
	belongs_to :modul
	belongs_to :ram_entry
	has_one :milestone, dependent: :destroy
end

app/models/estimation.rb
class Estimation < ActiveRecord::Base
	has_one :workpackage
	belongs_to :expert_form
end

app/models/expert_form.rb
class ExpertForm < ActiveRecord::Base
	belongs_to :round
	has_many :estimations, dependent: :destroy
end

app/models/form_template.rb
class FormTemplate < ActiveRecord::Base
	belongs_to :round
	has_many :estimation_templates, dependent: :destroy
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
	belongs_to :component
end

app/models/modul.rb
class Modul < ActiveRecord::Base
	belongs_to :subproduct
	has_many :components, dependent: :destroy
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_one :work_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :product_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :roadmap, dependent: :destroy, :foreign_key => "p_id"
	has_one :delphi_estimation, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_allocation_matrix, dependent: :destroy, :foreign_key => "p_id"
end

app/models/ram_entry.rb
class RamEntry < ActiveRecord::Base
	belongs_to :workpackage
	has_one :resource
	has_one :component
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :role
	belongs_to :ram_entry
	validates :quantitiy, :numericality => {:only_integer => true}
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
	belongs_to :project
	has_many :milestones, dependent: :destroy
end

app/models/role.rb
class Role < ActiveRecord::Base
	belongs_to :type
	has_many :resources, dependent: :destroy
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :delphi_estimation
	has_many :expert_forms, dependent: :destroy
	has_one :form_template, dependent: :destroy
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
	belongs_to :product_breakdown_structure
	has_many :moduls, dependent: :destroy
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
	belongs_to :task
	has_many :workpackages, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :work_breakdown_structure
	has_many :subtasks, dependent: :destroy
end

app/models/type.rb
class Type < ActiveRecord::Base
	belongs_to :resource_breakdown_structer
	has_many :roles, dependent: :destroy
end

app/models/workpackage.rb
class Workpackage < ActiveRecord::Base
	belongs_to :subtask
	has_one :ram_entry, dependent: :destroy
	belongs_to :estimation
	belongs_to :estimation_template
end

app/controllers/expert_forms_controller.rb
class ExpertFormsController < ApplicationController
  before_action :set_expert_form, only: [:show, :edit, :update, :destroy]

  # GET /expert_forms
  # GET /expert_forms.json
  def index
    @expert_forms = ExpertForm.all
  end

  # GET /expert_forms/1
  # GET /expert_forms/1.json
  def show
  end

  # GET /expert_forms/new
  def new
    @expert_form = ExpertForm.new(round_id: params[:round_id])
  end

  # GET /expert_forms/1/edit
  def edit
  end

  # POST /expert_forms
  # POST /expert_forms.json
  def create
    @expert_form = ExpertForm.new(expert_form_params)

    respond_to do |format|
      if @expert_form.save
        formTemplate = FormTemplate.find_by round_id: @expert_form.round_id
        estimationTemplates = EstimationTemplate.where(form_template_id: formTemplate.id)
        estimationTemplates.each do |estimationTemplate|
          Estimation.new(expert_form_id: @expert_form.id, workpackage_id: estimationTemplate.workpackage_id, duration: 0).save
        end
        format.html { redirect_to @expert_form, notice: 'Schätzungsformular wurde erfolgreich angelegt' }
        format.json { render :show, status: :created, location: @expert_form }
      else
        format.html { render :new }
        format.json { render json: @expert_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expert_forms/1
  # PATCH/PUT /expert_forms/1.json
  def update
    respond_to do |format|
      if @expert_form.update(expert_form_params)
        format.html { redirect_to @expert_form, notice: 'Schätzungsformular wurde erfolgreich aktualisiert' }
        format.json { render :show, status: :ok, location: @expert_form }
      else
        format.html { render :edit }
        format.json { render json: @expert_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expert_forms/1
  # DELETE /expert_forms/1.json
  def destroy
    @expert_form.destroy
    respond_to do |format|
      format.html { redirect_to expert_forms_url, notice: 'Schätzungsformular wurde erfolgreich gelöscht' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expert_form
      @expert_form = ExpertForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expert_form_params
      params.require(:expert_form).permit(:round_id, :expertName)
    end
end

app/helpers/expert_forms_helper.rb
module ExpertFormsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/expert_forms/_form.html.erb
<%= form_for(@expert_form) do |f| %>
  <% if @expert_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expert_form.errors.count, "error") %> prohibited this expert_form from being saved:</h2>

      <ul>
      <% @expert_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round_id %><br>
    <%= f.number_field :round_id %>
  </div>
  <div class="field">
    <%= f.label :expertName %><br>
    <%= f.text_field :expertName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expert_forms/edit.html.erb
<h1>Editing Expert Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @expert_form %> |
<%= link_to 'Back', expert_forms_path %>

app/views/expert_forms/index.html.erb
<h1>Listing Expert Forms</h1>

<table>
  <thead>
    <tr>
      <th>Round</th>
      <th>Expertname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expert_forms.each do |expert_form| %>
      <tr>
        <td><%= expert_form.round_id %></td>
        <td><%= expert_form.expertName %></td>
        <td><%= link_to 'Show', expert_form %></td>
        <td><%= link_to 'Edit', edit_expert_form_path(expert_form) %></td>
        <td><%= link_to 'Destroy', expert_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expert form', new_expert_form_path %>

app/views/expert_forms/new.html.erb
<h2>
  Bitte tragen Sie Ihren Namen ein
  <%= link_to 'Zurück zur Rundenübersicht', DelphiEstimation.find_by_id(Round.find_by_id(@expert_form.round_id).delphiEstimation_id), :id=>'btn', :class=> 'btn btn-sm btn-danger pull-right'%>
</h2>

<%= form_for(@expert_form) do |f| %>
  <% if @expert_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expert_form.errors.count, "error") %> prohibited this expert_form from being saved:</h2>

      <ul>
      <% @expert_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "form-inline">
 <div class="form-group">
  <%= f.hidden_field :round_id, :value => @expert_form.round_id %>
 </div>
<div class="field" id="new">
    <br>
    <%= f.text_field :expertName, :class => "form-control", placeholder:"Ihren Namen eintragen" %>
</div> 

<%= f.submit "Weiter zur Schätzung", class: "btn btn-sm btn-success" %>
<% end %>

app/views/expert_forms/show.html.erb
<h2><%= @expert_form.expertName. +', tragen Sie Ihre Schätzung ein.'%></h2>
<% estimations = Estimation.where(expert_form_id: @expert_form.id) %>
<table class="table">
	<thead>
		<tr>
			<th>Arbeitspaket</th>
			<th>Kommentar</th>
			<th>Schätzung (in Tagen)</th>
		</tr>
	</thead>
	<tbody>
		<% formTemplate = FormTemplate.find_by round_id: @expert_form.round_id %>
		<% estimationTemplates = EstimationTemplate.where(form_template_id: formTemplate.id) %>

		<% estimations.each do |estimation| %>
		<tr>
			<td><%= Workpackage.find_by_id(estimation.workpackage_id).name %></td>
			<td>
				<% estimationTemplates.each do |estimationTemplate| %>
					<%= if estimationTemplate.workpackage_id == estimation.workpackage_id then estimationTemplate.comment end %>
				<% end %>
			</td>
			<td>
				<div class = "form-inline">
	    		<%= form_for(estimation) do |f| %>
  				<div class="form-group">
	  				<div class="field">
	    				<%= f.number_field :duration, :class => "form-control input-sm"%>
	  				</div>
  				</div>
	  			<div class="form-group">
	  				<div class="actions">
	  					<%= f.submit "Speichern", class: "btn btn-xs btn-success" %>
	  				</div>
  				</div>
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'Schätzung abschließen', DelphiEstimation.find_by_id(Round.find_by_id(@expert_form.round_id).delphiEstimation_id), :id=>'btn' , class: "btn btn-sm btn-success"%>