config/routes.rb
Rails.application.routes.draw do
  resources :ram_entries
  resources :estimation_templates
  resources :estimations
  resources :milestones
  resources :roadmaps
  resources :expert_forms
  resources :form_templates
  resources :rounds
  resources :delphi_estimations
  resources :resource_allocation_matrices
  resources :resources
  resources :roles
  resources :types
  resources :subtasks
  resources :workpackages
  resources :tasks
  resources :components
  resources :moduls
  resources :subproducts
  resources :resource_breakdown_structures
  resources :product_breakdown_structures
  resources :work_breakdown_structures
  resources :projects

  get '/work_breakdown_structures/:id/chart' => 'work_breakdown_structures#chart', as: 'chart_work_breakdown_structure'
  get '/product_breakdown_structures/:id/chart' => 'product_breakdown_structures#chart', as: 'chart_product_breakdown_structure'
  get '/resource_breakdown_structures/:id/chart' => 'resource_breakdown_structures#chart', as: 'chart_resource_breakdown_structure'

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
	belongs_to :modul
	belongs_to :ram_entry
	has_one :milestone, dependent: :destroy
end

app/models/estimation.rb
class Estimation < ActiveRecord::Base
	has_one :workpackage
	belongs_to :expert_form
end

app/models/expert_form.rb
class ExpertForm < ActiveRecord::Base
	belongs_to :round
	has_many :estimations, dependent: :destroy
end

app/models/form_template.rb
class FormTemplate < ActiveRecord::Base
	belongs_to :round
	has_many :estimation_templates, dependent: :destroy
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
	belongs_to :component
end

app/models/modul.rb
class Modul < ActiveRecord::Base
	belongs_to :subproduct
	has_many :components, dependent: :destroy
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_one :work_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :product_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :roadmap, dependent: :destroy, :foreign_key => "p_id"
	has_one :delphi_estimation, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_allocation_matrix, dependent: :destroy, :foreign_key => "p_id"
end

app/models/ram_entry.rb
class RamEntry < ActiveRecord::Base
	belongs_to :workpackage
	has_one :resource
	has_one :component
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :role
	belongs_to :ram_entry
	validates :quantitiy, :numericality => {:only_integer => true}
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
	belongs_to :project
	has_many :milestones, dependent: :destroy
end

app/models/role.rb
class Role < ActiveRecord::Base
	belongs_to :type
	has_many :resources, dependent: :destroy
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :delphi_estimation
	has_many :expert_forms, dependent: :destroy
	has_one :form_template, dependent: :destroy
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
	belongs_to :product_breakdown_structure
	has_many :moduls, dependent: :destroy
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
	belongs_to :task
	has_many :workpackages, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :work_breakdown_structure
	has_many :subtasks, dependent: :destroy
end

app/models/type.rb
class Type < ActiveRecord::Base
	belongs_to :resource_breakdown_structer
	has_many :roles, dependent: :destroy
end

app/models/workpackage.rb
class Workpackage < ActiveRecord::Base
	belongs_to :subtask
	has_one :ram_entry, dependent: :destroy
	belongs_to :estimation
	belongs_to :estimation_template
end

app/controllers/workpackages_controller.rb
class WorkpackagesController < ApplicationController
  before_action :set_workpackage, only: [:show, :edit, :update, :destroy]

  # GET /workpackages
  # GET /workpackages.json
  def index
    @workpackages = Workpackage.all
  end

  # GET /workpackages/1
  # GET /workpackages/1.json
  def show
  end

  # GET /workpackages/new
  def new
    @workpackage = Workpackage.new
  end

  # GET /workpackages/1/edit
  def edit
  end

  # POST /workpackages
  # POST /workpackages.json
  def create
    @workpackage = Workpackage.new(workpackage_params)

    respond_to do |format|
      if @workpackage.save
        subtask = Subtask.find_by_id(@workpackage.subtask_id)
        task = Task.find_by_id(subtask.task_id)
        wbs = WorkBreakdownStructure.find_by_id(task.wbs_id)
        project = Project.find_by_id(wbs.p_id)
        ram = ResourceAllocationMatrix.find_by(p_id: project.id)

        RamEntry.new(workpackage_id: @workpackage.id, ram_id: ram.id).save
        format.html { redirect_to '/work_breakdown_structures/'+Task.find_by(id: Subtask.find_by(id: @workpackage.subtask_id).task_id).wbs_id.to_s+'/edit', notice: 'Workpackage wurde erfolgreich angelegt' }
        format.json { render :show, status: :created, location: @workpackage }
      else
        format.html { render :new }
        format.json { render json: @workpackage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workpackages/1
  # PATCH/PUT /workpackages/1.json
  def update
    respond_to do |format|
      if @workpackage.update(workpackage_params)
        format.html { redirect_to @workpackage, notice: 'Workpackage wurde erfolgreich aktualisiert' }
        format.json { render :show, status: :ok, location: @workpackage }
      else
        format.html { render :edit }
        format.json { render json: @workpackage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workpackages/1
  # DELETE /workpackages/1.json
  def destroy
    @workpackage.destroy
    respond_to do |format|
      format.html { redirect_to '/work_breakdown_structures/'+Task.find_by(id: Subtask.find_by(id: @workpackage.subtask_id).task_id).wbs_id.to_s+'/edit', notice: 'Workpackage wurde erfolgreich gelöscht' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workpackage
      @workpackage = Workpackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workpackage_params
      params.require(:workpackage).permit(:name, :subtask_id)
    end
end

app/helpers/moduls_helper.rb
module ModulsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/workpackages_helper.rb
module WorkpackagesHelper
end

app/views/workpackages/_form.html.erb
<%= form_for(@workpackage) do |f| %>
  <% if @workpackage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workpackage.errors.count, "error") %> prohibited this workpackage from being saved:</h2>

      <ul>
      <% @workpackage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subtask_id %><br>
    <%= f.number_field :subtask_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workpackages/edit.html.erb
<h1>Editing Workpackage</h1>

<%= render 'form' %>

<%= link_to 'Show', @workpackage %> |
<%= link_to 'Back', workpackages_path %>

app/views/workpackages/index.html.erb
<h1>Listing Workpackages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subtask</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workpackages.each do |workpackage| %>
      <tr>
        <td><%= workpackage.name %></td>
        <td><%= workpackage.subtask_id %></td>
        <td><%= link_to 'Show', workpackage %></td>
        <td><%= link_to 'Edit', edit_workpackage_path(workpackage) %></td>
        <td><%= link_to 'Destroy', workpackage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workpackage', new_workpackage_path %>

app/views/workpackages/new.html.erb
<h1>New Workpackage</h1>

<%= render 'form' %>

<%= link_to 'Back', workpackages_path %>

app/views/workpackages/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @workpackage.name %>
</p>

<p>
  <strong>Subtask:</strong>
  <%= @workpackage.subtask_id %>
</p>

<%= link_to 'Edit', edit_workpackage_path(@workpackage) %> |
<%= link_to 'Back', workpackages_path %>