config/routes.rb
Rails.application.routes.draw do
  resources :ram_entries
  resources :estimation_templates
  resources :estimations
  resources :milestones
  resources :roadmaps
  resources :expert_forms
  resources :form_templates
  resources :rounds
  resources :delphi_estimations
  resources :resource_allocation_matrices
  resources :resources
  resources :roles
  resources :types
  resources :subtasks
  resources :workpackages
  resources :tasks
  resources :components
  resources :moduls
  resources :subproducts
  resources :resource_breakdown_structures
  resources :product_breakdown_structures
  resources :work_breakdown_structures
  resources :projects

  get '/work_breakdown_structures/:id/chart' => 'work_breakdown_structures#chart', as: 'chart_work_breakdown_structure'
  get '/product_breakdown_structures/:id/chart' => 'product_breakdown_structures#chart', as: 'chart_product_breakdown_structure'
  get '/resource_breakdown_structures/:id/chart' => 'resource_breakdown_structures#chart', as: 'chart_resource_breakdown_structure'

  root 'projects#index'

end

app/models/component.rb
class Component < ActiveRecord::Base
	belongs_to :modul
	belongs_to :ram_entry
	has_one :milestone, dependent: :destroy
end

app/models/estimation.rb
class Estimation < ActiveRecord::Base
	has_one :workpackage
	belongs_to :expert_form
end

app/models/expert_form.rb
class ExpertForm < ActiveRecord::Base
	belongs_to :round
	has_many :estimations, dependent: :destroy
end

app/models/form_template.rb
class FormTemplate < ActiveRecord::Base
	belongs_to :round
	has_many :estimation_templates, dependent: :destroy
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
	belongs_to :component
end

app/models/modul.rb
class Modul < ActiveRecord::Base
	belongs_to :subproduct
	has_many :components, dependent: :destroy
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_one :work_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :product_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_breakdown_structure, dependent: :destroy, :foreign_key => "p_id"
	has_one :roadmap, dependent: :destroy, :foreign_key => "p_id"
	has_one :delphi_estimation, dependent: :destroy, :foreign_key => "p_id"
	has_one :resource_allocation_matrix, dependent: :destroy, :foreign_key => "p_id"
end

app/models/ram_entry.rb
class RamEntry < ActiveRecord::Base
	belongs_to :workpackage
	has_one :resource
	has_one :component
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :role
	belongs_to :ram_entry
	validates :quantitiy, :numericality => {:only_integer => true}
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
	belongs_to :project
	has_many :milestones, dependent: :destroy
end

app/models/role.rb
class Role < ActiveRecord::Base
	belongs_to :type
	has_many :resources, dependent: :destroy
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :delphi_estimation
	has_many :expert_forms, dependent: :destroy
	has_one :form_template, dependent: :destroy
end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
	belongs_to :product_breakdown_structure
	has_many :moduls, dependent: :destroy
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
	belongs_to :task
	has_many :workpackages, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :work_breakdown_structure
	has_many :subtasks, dependent: :destroy
end

app/models/type.rb
class Type < ActiveRecord::Base
	belongs_to :resource_breakdown_structer
	has_many :roles, dependent: :destroy
end

app/models/workpackage.rb
class Workpackage < ActiveRecord::Base
	belongs_to :subtask
	has_one :ram_entry, dependent: :destroy
	belongs_to :estimation
	belongs_to :estimation_template
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role_id %><br>
    <%= f.number_field :role_id %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br>
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </div>
  <div class="field">
    <%= f.label :quantitiy %><br>
    <%= f.text_field :quantitiy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Qualification</th>
      <th>Experience</th>
      <th>Quantitiy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.role_id %></td>
        <td><%= resource.qualification %></td>
        <td><%= resource.experience %></td>
        <td><%= resource.quantitiy %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p>
  <strong>Role:</strong>
  <%= @resource.role_id %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @resource.qualification %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @resource.experience %>
</p>

<p>
  <strong>Quantitiy:</strong>
  <%= @resource.quantitiy %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>